language: java
jdk:
  - oraclejdk8

services:
  - mysql

before_script:
  - mv src/main/resources/argos-backend_template.properties src/main/resources/argos-backend.properties

script:
  mvn test -B -V